on: push

name: Run tests
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DISPLAY: :99
    steps:
      - uses: actions/checkout@v3
      - name: Set up Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
      - run: yarn ci
